<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use App\Models\Karang;
use App\Models\Post;
use App\Models\User;
use Illuminate\Database\Seeder;

class KarangSeeder extends Seeder
{
    public function run()
    {
        foreach ($this->getKarangData() as $karangData) {
            // Ambil post dan user yang sesuai
            $post = Post::find($karangData['post_id']);
            $user = User::find($karangData['user_id']);

            // Buat Karang dan atur relasinya
            $karang = Karang::updateOrCreate($karangData);
            $karang->post()->associate($post);
            $karang->user()->associate($user);
            $karang->save();
        }
    }

    private function getKarangData()
    {
        return [
            [
                'post_id'       => '1',
                'user_id'       => '1',
                'algae'         => '0',
                'abiotik'       => '2.52',
                'biota_lain'    => '0',
                'karang_hidup'  => '22.14',
                'karang_mati'   => '75.34',
                'acb'           => '2.88',
                'acd'           => '0.86',
                'ace'           => '0',
                'acs'           => '0',
                'act'           => '12.82',
                'cb'            => '0.00',
                'cf'            => '1.04',
                'ce'            => '2.18',
                'cm'            => '2.36',
                'cs'            => '0.00',
                'cmr'           => '0.00',
                'chl'           => '0.00',
                'cme'           => '0.00',
                'dc'            => '38.54',
                'dca'           => '36.80',
            ],
            [
                'post_id'       => '2',
                'user_id'       => '1',
                'algae'         => '0',
                'abiotik'       => '8.88',
                'biota_lain'    => '0',
                'karang_hidup'  => '51',
                'karang_mati'   => '40.12',
                'acb'           => '6.24',
                'acd'           => '5.26',
                'ace'           => '3.06',
                'acs'           => '1.08',
                'act'           => '14.06',
                'cb'            => '0',
                'ce'            => '13.06',
                'cf'            => '0.26',
                'cm'            => '7.98',
                'cs'            => '0.00',
                'cmr'           => '0.00',
                'chl'           => '0.00',
                'cme'           => '0.00',
                'dc'            => '10.42',
                'dca'           => '29.70',
            ],
            [
                'post_id'       => '3',
                'user_id'       => '1',
                'algae'         => '0',
                'abiotik'       => '76.90',
                'biota_lain'    => '9.38',
                'karang_hidup'  => '11.46',
                'karang_mati'   => '2.26',
                'acb'           => '0.44',
                'acd'           => '0.66',
                'ace'           => '0.00',
                'acs'           => '0.44',
                'act'           => '0.00',
                'cb'            => '2.88',
                'ce'            => '4.40',
                'cf'            => '0.50',
                'cm'            => '1.76',
                'cs'            => '0.00',
                'cmr'           => '0.38',
                'chl'           => '0.00',
                'cme'           => '0.00',
                'dc'            => '0.00',
                'dca'           => '2.26',
            ],
            [
                'post_id'       => '4',
                'user_id'       => '1',
                'algae'         => '7.38',
                'abiotik'       => '61.48',
                'biota_lain'    => '0.0',
                'karang_hidup'  => '31.14',
                'karang_mati'   => '0',
                'acb'           => '3.76',
                'acd'           => '0.00',
                'ace'           => '0.62',
                'acs'           => '0.00',
                'act'           => '2.00',
                'cb'            => '0.00',
                'ce'            => '2.66',
                'cf'            => '0.00',
                'cm'            => '17.65',
                'cs'            => '2.62',
                'cmr'           => '0.00',
                'chl'           => '1.83',
                'cme'           => '0.00',
                'dc'            => '0.00',
                'dca'           => '0.00',
            ],
            [
                'post_id'       => '5',
                'user_id'       => '1',
                'algae'         => '5.48',
                'abiotik'       => '52.12',
                'biota_lain'    => '0.00',
                'karang_hidup'  => '35.40',
                'karang_mati'   => '7.00',
                'acb'           => '1.06',
                'acd'           => '0.00',
                'ace'           => '0.00',
                'acs'           => '0.00',
                'act'           => '0.00',
                'cb'            => '0.00',
                'ce'            => '1.26',
                'cf'            => '0.00',
                'cm'            => '8.62',
                'cs'            => '0.76',
                'cmr'           => '0.40',
                'chl'           => '23.30',
                'cme'           => '0.00',
                'dc'            => '0.42',
                'dca'           => '6.58',
            ],
            [
                'post_id'       => '6',
                'user_id'       => '1',
                'algae'         => '12.24',
                'abiotik'       => '44.14',
                'biota_lain'    => '0.16',
                'karang_hidup'  => '31.36',
                'karang_mati'   => '12.10',
                'acb'           => '0.76',
                'acd'           => '0.00',
                'ace'           => '0.00',
                'acs'           => '0.00',
                'act'           => '0.00',
                'cb'            => '0.00',
                'ce'            => '0.00',
                'cf'            => '0.72',
                'cm'            => '28.08',
                'cs'            => '1.80',
                'cmr'           => '0.00',
                'chl'           => '0.00',
                'cme'           => '0.00',
                'dc'            => '0.00',
                'dca'           => '12.10',
            ],
            [
                'post_id'       => '7',
                'user_id'       => '1',
                'algae'         => '20.14',
                'abiotik'       => '12.2',
                'biota_lain'    => '0.24',
                'karang_hidup'  => '66.76',
                'karang_mati'   => '0.66',
                'acb'           => '18.92',
                'acd'           => '0.34',
                'ace'           => '0.00',
                'acs'           => '0.00',
                'act'           => '0.22',
                'cb'            => '0',
                'ce'            => '16.18',
                'cf'            => '5.98',
                'cm'            => '6.50',
                'cs'            => '0.00',
                'cmr'           => '0.00',
                'chl'           => '0.00',
                'cme'           => '18.62',
                'dc'            => '0.00',
                'dca'           => '0.66',
            ],
            [
                'post_id'       => '8',
                'user_id'       => '1',
                'algae'         => '0.00',
                'abiotik'       => '42.30',
                'biota_lain'    => '0.56',
                'karang_hidup'  => '51.42',
                'karang_mati'   => '5.72',
                'acb'           => '27.76',
                'acd'           => '0.00',
                'ace'           => '0.00',
                'acs'           => '0.00',
                'act'           => '0.00',
                'cb'            => '6.36',
                'ce'            => '0.00',
                'cf'            => '12.04',
                'cm'            => '0.00',
                'cs'            => '0.00',
                'cmr'           => '0.00',
                'chl'           => '5.26',
                'cme'           => '0.00',
                'dc'            => '0.00',
                'dca'           => '5.72',
            ],
        ];
    }
}
